### ISSUE TITLE
Toplevel-Categories in article class übernehmen

### ISSUE THREAD

**Issue by freimair** [freimair/radlager-mtb#29]
und dann Bescheid sagen

**Comment by freimair** [comment]
wenn du eh nur dinge, dich nicht Fotoblog sind anders einfärben willst hammas eigentlich schon. Es gibt:

- category-fotoblog-trailbau-villach
- category-presse
- category-news
- (zukünftig) category-fotoblog-trailbau-graz

und im CSS kann man doch ein logisches UND setzen oder? Das sollte doch reichen um die Dinger zu unterscheiden.

**Comment by zaila99** [comment]
läuft
